apiVersion: v1
kind: Service
metadata:
  name: flask-red-service
spec:
  type: NodePort
  selector:
    app: flask-red
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-green-service
spec:
  type: NodePort
  selector:
    app: flask-green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
